const ROUTES = {
  NEW_TASK: 'new-task',
  TASK: 'task'
};

const INPUT_FLAG_REDUCERS_TYPE = {
  INPUT_TITLE: 'INPUT_TITLE',
  INPUT_DESCRIPTION: 'INPUT_DESCRIPTION',
  INPUT_STATUS: 'INPUT_STATUS',
  INPUT_LABEL: 'INPUT_LABEL',
  INPUT_PRIORITY: 'INPUT_PRIORITY'
};

const INPUT_FORM_REDUCERS_TYPE = {
  TITLE: 'TITLE',
  DESCRIPTION: 'DESCRIPTION',
  LABEL: 'LABEL',
  PRIORITY: 'PRIORITY'
};

const STORAGE_TYPE = {
  TASK: 'TASK'
}

export {
  ROUTES,
  INPUT_FLAG_REDUCERS_TYPE,
  INPUT_FORM_REDUCERS_TYPE,
  STORAGE_TYPE
}